import { Header, Footer, ClientProgressProvider } from "./components";
import { headers } from 'next/headers'
import Script from "next/script";
import { Suspense } from "react";
import { Poppins } from "next/font/google";
import { Montserrat } from 'next/font/google';
import { Roboto_Slab } from "next/font/google"
import "./globals.css";

const robotoSlab = Roboto_Slab({
  subsets: ['latin'],
  variable: '--font-roboto-slab',
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
})

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Custom Pack Boxes - Premium Packaging Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const headersList = headers()
  const pathname = headersList.get('x-pathname') || ''
  const isThankYouPage = pathname === '/thank-you'
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${robotoSlab.variable}  antialiased`}
      >
        <Script
          id="gtm-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-K238CTPC');`,
          }}
        />
        <noscript><iframe
          src="https://www.googletagmanager.com/ns.html?id=GTM-K238CTPC"
          height="0"
          width="0"
          style={{ display: "none", visibility: "hidden" }} 
        ></iframe>
        </noscript>

        <Suspense>
          <ClientProgressProvider>
            {!isThankYouPage && <Header />}
            {children}
            {!isThankYouPage && <Footer />}
          </ClientProgressProvider>
        </Suspense>
         <Script
          id="tawk-to"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
              (function(){
                var s1=document.createElement("script"),
                    s0=document.getElementsByTagName("script")[0];
                s1.async=true;
                s1.src='https://embed.tawk.to/670d3c8d4304e3196ad168de/1ia5r9330';
                s1.charset='UTF-8';
                s1.setAttribute('crossorigin','*');
                s0.parentNode.insertBefore(s1,s0);
              })();
            `,
          }}
        />
      </body>
    </html>
  );
}
